apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: lockbox-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: lockbox-controller
subjects:
  - kind: ServiceAccount
    name: lockbox-controller
    namespace: lockbox
